# Generated by Django 4.2 on 2024-12-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
