# Generated by Django 4.2 on 2024-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
