# Generated by Django 4.2 on 2024-12-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_job_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
