# Generated by Django 4.2 on 2024-12-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazilink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
