# Generated by Django 4.2 on 2024-12-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
